backup:
  dry_run: true
  services: ["traefik"]
  zpool:
    name: zroot
    directory: /.backup
    datasets: ["nixos", "srv"]

motd:
  modules:
    - module: system

    - module: flake
      file: data/motd/flake.json

    - module: services
      units: ["running", "succeeded", "failed"]
      tasks: ["running", "succeeded", "failed"]

secret:
  dry_run: true
  file: data/secret/podman.yaml
