backup:
  dry_run: true
  services: ["traefik"]
  zpool:
    name: zroot
    directory: /.backup
    datasets: ["nixos", "srv"]

motd:
  modules:
    - module: system

    - module: update
      file: data/motd/update.json

    - module: services
      units: ["traefik"]
      tasks: ["backup"]

secret:
  dry_run: true
  file: data/secret/podman.yaml
