name: "Flake: Update"

on:
  workflow_dispatch:
    inputs:
      nixpkgsOnly:
        description: Update nixpkgs only?
        required: true
        default: true
        type: boolean


  schedule:
    - cron: "0 0 * * 0"

jobs:
  flake-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          determinate: false

      - name: Use nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          use-flakehub: false

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v28
        if: ${{ inputs.nixpkgsOnly == 'true' }}
        with:
          pr-title: "Flake: Update nixpkgs"
          pr-labels: automated

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v28
        if: ${{ inputs.nixpkgsOnly == 'false' }}
        with:
          inputs: nixpkgs
          pr-title: "Flake: Update nixpkgs"
          pr-labels: automated
